# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Submit a new Beta Build to App Store"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "HVFB8BQNRL",
      issuer_id: "7ccdd7c6-559b-43a1-aa33-b6e65510900f",
      key_filepath: "./../config/AuthKey_HVFB8BQNRL.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

    sh "flutter build ipa --dart-define-from-file=config/config.json --release --export-method=app-store"

    upload_to_testflight(
      ipa: "../build/ios/ipa/#{app_name}.ipa",
      skip_waiting_for_build_processing: true,
      api_key: api_key
    )
  end
end
